# Generated by Django 3.0.4 on 2020-04-01 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0002_auto_20200401_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Member',
        ),
    ]
