# Generated by Django 3.0.4 on 2020-04-01 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0003_auto_20200401_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Profile',
        ),
    ]
