# Generated by Django 3.0.4 on 2020-04-01 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200401_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_of_loan',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2020, 4, 23)),
        ),
    ]
