# Generated by Django 3.0.4 on 2020-04-15 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20200402_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_of_loan',
            field=models.DateField(default=datetime.date(2020, 4, 15)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2020, 5, 6)),
        ),
    ]
